configuration: 
  name: hellobioqa
  author: team06
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: hellobioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  #file: /input/oneQ.txt
  #file: /input/tenQ.txt
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      #- inherit: hellobioqa.team06.keyterm.KeyTermParser
      #- inherit: hellobioqa.team06.keyterm.KeyTermFilter #Check and see if Varuni's performs better than LingPipe
      #- inherit: helloqa.keyterm.simple
      #- inherit: hellobioqa.team06.keyterm.KentonKeytermExtractor
      #- inherit: hellobioqa.team06.keyterm.KeyTermParser
      #- inherit: hellobioqa.team06.keyterm.KeyTermFilter
      - inherit: hellobioqa.team06.keyterm.ShuBannerExtractor
      #- inherit: hellobioqa.team06.keyterm.Shu_Hao_KeyExtractor
      #- inherit: hellobioqa.team06.keyterm.vgangkeytermExtractor
      #- inherit: helloqa.keyterm.simple
  #- inherit: jdbc.sqlite.cse.phase
  #  name: keyterm-updater
  #  options: |
  #     - inherit: hellobioqa.team06.keyterm.ShuNLPVerbTermUpdater
  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: hellobioqa.team06.retrieval.simple-solr-strategist
          
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      - inherit: hellobioqa.team06.passage.simple
      
  - inherit: helloqa.eval.keyterm-aggregator-consumer

  - inherit: jdbc.eval.retrieval-aggregator-consumer
      
  - inherit: helloqa.eval.passage-map-aggregator-consumer      
    
post-process: 
  - inherit: helloqa.eval.keyterm-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.keyterm-report-component

  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
          
  - inherit: helloqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.map-report-component
  
